# Generated by Django 2.2.6 on 2019-10-25 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystudio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='link',
            field=models.CharField(default='', max_length=250),
        ),
    ]
